'use client';
import { useEffect,useMemo,useState } from 'react';
type Incident={id:string;title:string;deviceId:string;lane:string;faultCode:string;status:string;deviceType:string;evidence:Record<string,unknown>}; type Proposal={id:string;incidentId:string;diagnosisSummary:string;recommendation:string;rationale:string;safetyChecks:string[];expectedOutcome:string;limits:string[];evidenceRefs:string[];evidenceVersion:number;expiresAt:string};
export default function Page(){const [data,setData]=useState<any>();const [selected,setSelected]=useState('INC-101');const [proposal,setProposal]=useState<Proposal>();const [events,setEvents]=useState<any[]>([]);const [busy,setBusy]=useState(false);const [sales,setSales]=useState('');const [error,setError]=useState('');const incident:Incident|undefined=data?.incidents.find((i:Incident)=>i.id===selected);const risk=useMemo(()=>sales&&incident?Math.round((Number(sales)/60)*(Number(incident.evidence['telemetry.offlineSeconds']||180)/60)*100)/100:null,[sales,incident]);
 const load=async()=>setData(await (await fetch('/api/state')).json()); useEffect(()=>{load()},[]); useEffect(()=>{const t=setInterval(load,1000);return()=>clearInterval(t)},[]);
 async function diagnose(){setBusy(true);setError('');setProposal(undefined);try{const r=await (await fetch('/api/diagnose',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({incidentId:selected})})).json();if(r.error)throw Error(r.error);setProposal(r.proposal);setEvents(r.events||[]);await load()}catch(e){setError(e instanceof Error?e.message:'Diagnosis failed')}finally{setBusy(false)}}
 async function action(decision:'approve'|'reject'){if(!proposal)return;setBusy(true);setError('');try{const r=await (await fetch('/api/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({proposal,decision})})).json();if(r.error)throw Error(r.error);await load()}catch(e){setError(e instanceof Error?e.message:'Action refused')}finally{setBusy(false)}}
 async function reset(){await fetch('/api/reset',{method:'POST'});setProposal(undefined);setEvents([]);await load()}
 if(!data||!incident)return <main className="loading">Loading workspace…</main>;
 const blocked=incident.status==='MANUAL_REVIEW'||incident.evidence['transaction.active']===true;
 return <main><header><div><p className="eyebrow">JUNIPER CAFE · DEVICE OPS</p><h1>Merchant Rescue</h1><p className="sub">Protect checkout continuity with evidence, approval, and a safe handoff.</p></div><div className="badges"><span className="badge synthetic">SYNTHETIC MERCHANT DATA / SANDBOX ACTIONS</span><span className="badge">{data.mode}</span></div></header>
 <section className="pnl"><label>Merchant&apos;s lost sales per hour ($)<input aria-label="Merchant's lost sales per hour ($)" inputMode="decimal" value={sales} onChange={e=>setSales(e.target.value)} placeholder="Enter owner estimate"/></label><span>{risk?`Sales at risk: $${risk.toFixed(2)} · per merchant's own estimate`:'Ask any owner: what does one hour of POS downtime cost you? No dollar claim is shown until they provide it.'}</span></section>
 <div className="layout"><aside className="panel"><div className="panelHead"><h2>Demo scenarios</h2><button className="quiet" onClick={reset}>Reset demo</button></div>{data.incidents.map((i:Incident)=><button className={`scenario ${i.id===selected?'selected':''}`} key={i.id} onClick={()=>{setSelected(i.id);setProposal(undefined);setEvents([])}}><strong>{i.id}</strong><span>{i.title}</span><small>{i.deviceId} · {i.lane}</small><em>{i.status.replaceAll('_',' ')}</em></button>)}</aside>
 <section className="panel detail"><div className="panelHead"><div><p className="eyebrow">INCIDENT DETAIL</p><h2>{incident.title}</h2></div><span className={`state ${blocked?'danger':''}`}>{incident.status.replaceAll('_',' ')}</span></div><div className="facts"><div><small>Device</small><strong>{incident.deviceId}</strong></div><div><small>Fault</small><strong>{incident.faultCode}</strong></div><div><small>Lane</small><strong>{incident.lane}</strong></div></div><div className="timeline"><h3>Agent activity</h3>{events.length?events.map((e,i)=><div className="event" key={i}><i></i><div><strong>{e.label}</strong><p>{e.detail}</p><time>{new Date(e.at).toLocaleTimeString()}</time></div></div>):<p className="muted">Run a diagnosis to see actual ZooWork or fixture activity here.</p>}</div><button className="primary wide" disabled={busy} onClick={diagnose}>{busy?'Working…':'Run diagnosis'}</button>{error&&<div className="error">{error}</div>}{incident.status==='VERIFYING'&&<div className="pending">Verification pending · waiting for a separate synthetic heartbeat.</div>}{incident.status==='RECOVERED_SIMULATION'&&<div className="success">Recovered in simulation · follow-up heartbeat is online.</div>}</section>
 <aside className="panel decision"><p className="eyebrow">DECISION GATE</p><h2>{proposal?'Proposal ready':'No proposal yet'}</h2>{proposal?<><div className="recommend"><small>Recommended sandbox action</small><strong>{proposal.recommendation.replaceAll('_',' ')}</strong></div><p className="diagnosis">{proposal.diagnosisSummary}</p><h3>Why</h3><p>{proposal.rationale}</p><h3>Safety checks</h3><ul>{proposal.safetyChecks.map(x=><li key={x}>{x}</li>)}</ul><h3>Evidence used</h3><div className="refs">{proposal.evidenceRefs.map(x=><code key={x}>{x}</code>)}</div><h3>Limits</h3><ul>{proposal.limits.map(x=><li key={x}>{x}</li>)}</ul>{proposal.recommendation==='ESCALATE_ONLY'?<div className="blocked">Restart blocked: a sale is in progress. Wait for the sale to end or record manual review. No restart button is available.</div>:<div className="actions"><button className="primary" disabled={busy} onClick={()=>action('approve')}>Approve sandbox action</button><button className="quiet" disabled={busy} onClick={()=>action('reject')}>Reject</button></div>}</>:<div className="empty">{blocked?'This scenario demonstrates restraint: the agent must refuse a restart during an active transaction.':'Evidence and policy will appear after diagnosis.'}</div>}</aside></div>
 <section className="audit panel"><details><summary>Audit trail · {data.audit.length} records</summary>{data.audit.length?data.audit.map((a:any)=><div className="auditrow" key={a.id}><time>{new Date(a.at).toLocaleTimeString()}</time><strong>{a.type}</strong><span>{a.detail}</span></div>):<p className="muted">No operator decision or sandbox action recorded yet.</p>}{data.ticket&&<div className="ticket"><h3>Sandbox ticket {data.ticket.id}</h3><strong>Needs physical inspection</strong><ul>{data.ticket.checklist.map((x:string)=><li key={x}>{x}</li>)}</ul><small>Internal record only · no technician dispatched · no repair claimed</small></div>}</details></section><footer>Monday test: connect a cafe&apos;s reader/printer status feed. Real today: ZooWork agent and approval flow. Synthetic today: telemetry and device actions.</footer></main>}
