import { Incident } from './types';
const now=()=>new Date().toISOString();
export const makeFixtures=():Incident[]=>[
 {id:'INC-101',title:'Checkout connection lost',deviceId:'POS-01',deviceType:'POS',lane:'Lane 1',faultCode:'DEMO_POS_LINK_DOWN',status:'DETECTED',evidenceVersion:1,evidence:{'telemetry.connection':'offline','telemetry.offlineSeconds':180,'telemetry.heartbeatAgeSeconds':20,'transaction.active':false,'security.tamperSignal':false,'actions.restartAttempts':0},history:['Connectivity drop','Reconnect failed','No active sale'],actionCount:0,createdAt:now()},
 {id:'INC-102',title:'Receipt printer jam',deviceId:'PRINTER-02',deviceType:'PRINTER',lane:'Lane 2',faultCode:'DEMO_PAPER_PATH_JAM',status:'DETECTED',evidenceVersion:1,evidence:{'telemetry.repeatedJamCount':3,'telemetry.windowMinutes':30,'telemetry.paperPresent':true,'telemetry.observedAgeSeconds':20,'security.tamperSignal':false},history:['Three jams in 30 minutes'],actionCount:0,createdAt:now()},
 {id:'INC-103',title:'Checkout connection lost during sale',deviceId:'POS-01',deviceType:'POS',lane:'Lane 1',faultCode:'DEMO_POS_LINK_DOWN',status:'DETECTED',evidenceVersion:1,evidence:{'telemetry.connection':'offline','telemetry.offlineSeconds':180,'telemetry.heartbeatAgeSeconds':20,'transaction.active':true,'security.tamperSignal':false,'actions.restartAttempts':0},history:['Connectivity drop','Active sale detected'],actionCount:0,createdAt:now()}
];
export const RUNBOOKS:Record<string,string>={DEMO_POS_LINK_DOWN:'One operator-approved connection-service restart is permitted only with fresh evidence, no active or unknown transaction, and no tamper signal.',DEMO_PAPER_PATH_JAM:'Repeated jams require onsite inspection of paper loading/path and rollers. Logs do not establish a worn roller or replacement part.'};
export const POLICY='Never restart with an active or unknown transaction. One approved restart per incident. Tamper, stale evidence, or contradictory telemetry requires manual review.';
