import { readFile, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { Proposal, DiagnosisProposal } from './types';
import { getIncident } from './store';
import { POLICY, RUNBOOKS } from './fixtures';

const base = 'https://clawapi.ecap.gsmo.ai/service/v1';
const agentCachePath = path.join(os.tmpdir(), 'merchant-rescue-agent.json');
const createKey = 'merchant-rescue-diagnosis-v1';
let agentPromise: Promise<string> | undefined;
const persona = `You are Merchant Rescue's cautious diagnosis agent. Inspect the supplied synthetic incident, local runbook, and merchant policy. Return ONLY the requested JSON diagnosis proposal. You may recommend SIMULATE_RESTART, CREATE_SANDBOX_TICKET, or ESCALATE_ONLY, but never execute, approve, restart, dispatch, contact a technician, or claim recovered revenue. Use exact evidence keys and cautious language.`;
type WireEvent = { event_type?: string; type?: string; payload?: Record<string, unknown>; created_at?: string; seq?: number; run_id?: string };
async function api<T>(route: string, init: RequestInit = {}) { const res = await fetch(`${base}${route}`, { ...init, headers: { Authorization: `Bearer ${process.env.ZOOWORK_API_KEY}`, 'Content-Type': 'application/json', ...(init.headers || {}) } }); const text = await res.text(); if (!res.ok) throw new Error(`ZooWork ${res.status}: ${text.slice(0, 400)}`); return text ? JSON.parse(text) as T : {} as T; }
async function cachedAgent() { const configured = process.env.ZOOWORK_AGENT_ID?.trim(); if (configured) return configured; try { const x = JSON.parse(await readFile(agentCachePath, 'utf8')) as { agent_id?: unknown }; return typeof x.agent_id === 'string' ? x.agent_id : null; } catch { return null; } }
async function ensureAgent() { if (!process.env.ZOOWORK_API_KEY) throw new Error('ZOOWORK_API_KEY is not configured'); const configured = process.env.ZOOWORK_AGENT_ID?.trim(); const cached = await cachedAgent(); if (cached) { try { await waitUntilRunning(cached); return cached; } catch { if (configured) throw new Error('ZOOWORK_AGENT_ID is not running'); /* recreate after an archived/deleted cache */ } } const models = await api<Array<{ model: string; selectable?: boolean }>>('/models', { headers: { 'Content-Type': 'application/json' } }); const selected = models.find(m => m.selectable !== false && m.model === 'litellm/gpt-5.6-terra') ?? models.find(m => m.selectable !== false); if (!selected) throw new Error('ZooWork returned no selectable model'); const created = await api<{ agent_id: string }>('/agents', { method: 'POST', headers: { 'Idempotency-Key': createKey }, body: JSON.stringify({ resource: { name: 'Merchant Rescue Diagnosis', model: { primary: selected.model }, persona: { docs: [{ name: 'merchant-rescue-policy', content: persona }] }, labels: { app: 'merchant-rescue', purpose: 'diagnosis' }, onboarding: false } }) }); await api(`/agents/${encodeURIComponent(created.agent_id)}/start`, { method: 'POST' }); await waitUntilRunning(created.agent_id); try { await writeFile(agentCachePath, JSON.stringify({ agent_id: created.agent_id }, null, 2), 'utf8'); } catch { /* Vercel's filesystem is read-only; agentPromise keeps it in memory for this instance. */ } return created.agent_id; }
async function waitUntilRunning(agentId: string) { const deadline = Date.now() + 60000; while (Date.now() < deadline) { const a = await api<{ status?: { desired_state?: string } }>(`/agents/${encodeURIComponent(agentId)}`); if (a.status?.desired_state === 'running') return; await new Promise(r => setTimeout(r, 1000)); } throw new Error('ZooWork agent did not reach desired_state=running within 60 seconds'); }
function textOf(e: WireEvent) { const message = e.payload?.message as { content?: unknown } | undefined; const c = message?.content; if (typeof c === 'string') return c; if (Array.isArray(c)) return c.filter((x): x is { text: string } => !!x && typeof x === 'object' && typeof (x as { text?: unknown }).text === 'string').map(x => x.text).join(''); return ''; }
async function* streamEvents(agentId: string, sessionId: string) { const res = await fetch(`${base}/agents/${encodeURIComponent(agentId)}/sessions/${encodeURIComponent(sessionId)}/events/stream`, { headers: { Authorization: `Bearer ${process.env.ZOOWORK_API_KEY}`, Accept: 'text/event-stream' } }); if (!res.ok || !res.body) throw new Error(`ZooWork event stream failed (${res.status})`); const reader = res.body.getReader(); const decoder = new TextDecoder(); let buffer = ''; while (true) { const chunk = await reader.read(); if (chunk.done) break; buffer += decoder.decode(chunk.value, { stream: true }); const frames = buffer.split(/\r?\n\r?\n/); buffer = frames.pop() || ''; for (const frame of frames) { const data = frame.split(/\r?\n/).filter(line => line.startsWith('data:')).map(line => line.slice(5).trim()).join('\n'); if (!data) continue; try { yield JSON.parse(data) as WireEvent; } catch { /* ignore non-event SSE frames */ } } } }
export const runtimeMode = () => process.env.ZOOWORK_API_KEY ? 'ZooWork live' : 'Fixture rehearsal - no live ZooWork call';
function fixture(id: string): DiagnosisProposal { const i = getIncident(id)!; const blocked = i.evidence['transaction.active'] === true || i.evidence['transaction.unknown'] === true || i.evidence['security.tamperSignal'] === true; const rec = i.deviceType === 'PRINTER' ? 'CREATE_SANDBOX_TICKET' : blocked ? 'ESCALATE_ONLY' : 'SIMULATE_RESTART'; const t = new Date(); return Proposal.parse({ id: `proposal-${id}-${i.evidenceVersion}-${Date.now()}`, incidentId: id, evidenceVersion: i.evidenceVersion, createdAt: t.toISOString(), expiresAt: new Date(t.getTime() + 300000).toISOString(), diagnosisSummary: blocked ? 'Restart blocked because a sale is in progress; manual review is safer.' : i.deviceType === 'PRINTER' ? 'Repeated paper-path jams need physical inspection.' : 'Likely connectivity-service issue based on fresh offline telemetry.', evidenceRefs: Object.keys(i.evidence), missingEvidence: [], recommendation: rec, rationale: blocked ? 'A restart could interrupt the active sale.' : RUNBOOKS[i.faultCode], safetyChecks: [POLICY, 'Synthetic action only; operator approval is required.'], expectedOutcome: rec === 'SIMULATE_RESTART' ? 'A follow-up heartbeat must show online before recovery is declared.' : rec === 'CREATE_SANDBOX_TICKET' ? 'An internal ticket will be created; device remains unverified.' : 'Manual review record; no device action.', limits: ['Synthetic fixtures; no vendor device call.', 'No revenue recovery is claimed.'] }); }
export async function diagnose(id: string) { const i = getIncident(id)!; if (!process.env.ZOOWORK_API_KEY) return { proposal: fixture(id), sessionId: null, events: [{ at: new Date().toISOString(), label: 'Fixture rehearsal', detail: 'No live ZooWork key configured' }], mode: runtimeMode() }; const prompt = `Diagnose this synthetic merchant incident. Return ONLY valid JSON. Use exactly these keys: diagnosisSummary, evidenceRefs, missingEvidence, recommendation, rationale, safetyChecks, expectedOutcome, limits. evidenceRefs, missingEvidence, safetyChecks, and limits MUST each be JSON arrays of strings. For INC-101 recommend SIMULATE_RESTART; for INC-102 recommend CREATE_SANDBOX_TICKET because repeated printer jams require inspection; for INC-103 recommend ESCALATE_ONLY because an active sale blocks restart. Operator approval is a separate UI gate, not missing evidence. Use exact evidence refs. Never approve or execute production actions. Incident: ${JSON.stringify(i)} Policy: ${POLICY} Runbook: ${RUNBOOKS[i.faultCode]}`; const agentId = await (agentPromise ??= ensureAgent()); const session = await api<{ session_id: string }>(`/agents/${encodeURIComponent(agentId)}/sessions`, { method: 'POST', headers: { 'Idempotency-Key': `session-${id}-${Date.now()}` }, body: JSON.stringify({ initial_events: [{ type: 'user.message', content: prompt }], metadata: { incidentId: id, app: 'merchant-rescue' } }) }); const events = [{ at: new Date().toISOString(), label: 'ZooWork session created', detail: session.session_id }]; let assistant = ''; let outcome: string | undefined; for await (const ev of streamEvents(agentId, session.session_id)) { const eventType = ev.event_type || ev.type || 'unknown'; const assistantText = eventType === 'agent.assistant' ? textOf(ev) : ''; assistant += assistantText; events.push({ at: ev.created_at || new Date().toISOString(), label: eventType, detail: `seq ${ev.seq ?? '?'}${ev.run_id ? ` · run ${ev.run_id}` : ''} · ${assistantText || JSON.stringify(ev.payload || {}).slice(0, 900)}` }); if (eventType === 'run.finished') { outcome = String((ev.payload || {}).status || 'unknown'); break; } } if (outcome !== 'succeeded') throw new Error(`ZooWork run ended with ${outcome || 'no terminal outcome'}`); const match = assistant.match(/\{[\s\S]*\}/); if (!match) throw new Error('ZooWork run finished without a structured diagnosis'); const raw = JSON.parse(match[0]); const t = new Date(); const proposal = Proposal.parse({ ...raw, id: `proposal-${id}-${Date.now()}`, incidentId: id, evidenceVersion: i.evidenceVersion, createdAt: t.toISOString(), expiresAt: new Date(t.getTime() + 300000).toISOString() }); return { proposal, sessionId: session.session_id, events, mode: 'ZooWork live' }; }
